name: Prod build
run-name: Build release files ðŸš€
on: [push]
jobs:
  Run-PSScriptAnalyzer-on-Windows:
    name: Run PSScriptAnalyzer on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PSScriptAnalyzer module
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module ps2exe
      - name: Get list of rules
        shell: powershell
        run: |
          . ps2exe users.ps1
